FROM bkjeholt/base-mydumper:dev-x86

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apt-get install -y ftp

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

RUN chmod -f 755 /usr/local/bin/dropbox-uploader/* 
